
def onCook(scriptOp):
	scriptOp.clear()
	i=0
	scriptOp.numSamples=len(parent.curycue.GetActiveEvaluators())
	newChan=scriptOp.appendChan("fades")
	for myEval in parent.curycue.GetActiveEvaluators():
		#print ("{}:{}".format(myEval.task.progress, myEval.task.name))
		# print (parent.curycue.GetActiveEvaluators()[myEval])
		
		
		newChan[i]=myEval.task.progress
		i+=1

	# for cue in parent.curycue.LocalCueData:
	# 	if cue.id==scriptOp.par.Cueid:
	# 		for cuePars in cue.pars_float:
	# 			if cuePars.par_text_value=='':
	# 				newChan=scriptOp.appendChan(cuePars.full_par_path)
	# 				newChan[0]=cuePars.par_value
	
	return

def onPulse(par):
	return

def onSetupParameters(scriptOp):
	"""Auto-generated by Component Editor"""
	# manual changes to anything other than parJSON will be	# destroyed by Comp Editor unless doc string above is	# changed

	TDJSON = op.TDModules.mod.TDJSON
	parJSON = """
	{}
	"""
	parData = TDJSON.textToJSON(parJSON)
	TDJSON.addParametersFromJSONOp(scriptOp, parData, destroyOthers=True)