
def onCook(scriptOp):
	if hasattr(parent.curycue.ext, "CuryCueClass"): 
		scriptOp.clear()
		for device in parent.curycue.LocalFixtureData:
			#device=op.curycue.LocalFixtureData[int(scriptOp.par.Cueid)]
			for devicePar in device.pars:
				chanName="{}:{}".format(devicePar.global_object_location, devicePar.par_name)
				newChan=scriptOp.appendChan(chanName)
				newChan[0]=devicePar.default_value
	return

def onPulse(par):
	return

def onSetupParameters(scriptOp):
	"""Auto-generated by Component Editor"""
	# manual changes to anything other than parJSON will be	# destroyed by Comp Editor unless doc string above is	# changed

	TDJSON = op.TDModules.mod.TDJSON
	parJSON = """
	{
		"Settings": {
			"Cueid": {
				"name": "Cueid",
				"label": "Cueid",
				"page": "Settings",
				"style": "Int",
				"size": 1,
				"default": 0,
				"enable": true,
				"startSection": false,
				"readOnly": false,
				"enableExpr": null,
				"min": 0.0,
				"max": 1.0,
				"normMin": 0.0,
				"normMax": 1.0,
				"clampMin": false,
				"clampMax": false
			}
		}
	}
	"""
	parData = TDJSON.textToJSON(parJSON)
	TDJSON.addParametersFromJSONOp(scriptOp, parData, destroyOthers=True)